apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi-deployment
  labels:
    app: authapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - name: authapi
        image: bestilmere/authapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authapi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: authapi
  type: ClusterIP

