apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-deployment
  labels:
    app: orderapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: bestilmere/orderapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orderapi-lb
spec:
  ports:
  - name: http
    port: 53001
    protocol: TCP
    targetPort: 80
  selector:
    app: orderapi
  type: LoadBalancer

