name: Docker Build, Publish & Azure Deploy

env:
  CLUSTER_NAME: bestilmere
  CLUSTER_RESOURCE_GROUP: bestil-mere
  NAMESPACE: default

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      DOCKER_REGISTRY: "bestilmere/"
      DOCKER_USERNAME: "peacedealer"

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
       echo -n ${{ secrets.REGISTRY_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
       cd Bestil-Mere
       docker-compose build
       docker-compose push
       
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v2
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Apply manifests incase of changes
    - run: kubectl apply -f ./Bestil-Mere/kube-manifests
    
    # Rollout new deployemnt to get new images
    - run: kubectl rollout restart deployment
